### ISSUE TITLE
Team hozzárendelése JSON Pimp feladathoz

### ISSUE THREAD

**Issue by gboldi19** [Teaching-projects/SZE-MOSZE-2020-Mortar_Kombat#19]
@hegyhati sajnálatos módon mi is úgy jártunk, hogy az a csapat, aki eddig reviewolt minket lezárásra került, emiatt szeretnénk kérelmezni @Teaching-projects/amd_bike csapat hozzáadását a repo-nkhoz, hogy ne csak mint szak-, de sorstársak (az ő review team-ük is kiesett) folytathassuk a továbbiakban

**Comment by hegyhati** [comment]
done.
