### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by balazs482** [Teaching-projects/SZE-MOSZE-2020-Mortar_Kombat#24]
A határidőre a game/map branch félig, és az utolsó körös feladatok egyáltalán nem készültek el. A Report jelenlegi állapota az imént került be a masterre, de annak a befejezése is hátra van. Ezeken  továbbra is dolgozunk, így reméljük, opció a vizsgaalkalom előtti befejezés és értékeltetés. Egy commentet írok ehhez az issuehoz, ha az aktuális állapotot hűen tükröző Report.md és videók elkészültek.

**Comment by hegyhati** [comment]
No, hat ugye ez meg igy nem ertekelesre kesz. Vizsgara mar egyeni projektekkel kell nevezni, szoval en azt javasolnam, hogy gyorsan csinaljatok meg a reportot, reassignoljatok, megajanlom, amit megajanlok az alapjan, aztan utana aki akar szoloban vizsgazhat. De a Team irany szerintem egyszerubb.

**Comment by Parmama** [comment]
Updateltük a reportot.
Van még lehetőségünk tartalmilag bővíteni a kódot akár megajánlott, akár vizsgajegyes értékelési időpontig?

**Comment by hegyhati** [comment]
Balazs-4
Boldizsar-3
Robert-2

Csapatos elbiraltatasra eddig volt lehetoseg, mostantol szoloprojekttel lehet "nevezni" vizsgara.

**Comment by gboldi19** [comment]
@hegyhati ezek a megajánlott jegyeink?

**Comment by hegyhati** [comment]
igen

**Comment by gboldi19** [comment]
Akkor köszönjük szépen, mindegyikünk egyetért! 😄
