### ISSUE TITLE
Activate Github Pages for code documentation

### ISSUE THREAD

**Issue by Parmama** [Teaching-projects/SZE-MOSZE-2020-Mortar_Kombat#8]
Could you please help me to generate URL for GitHub pages?   
The source is: **gh-pages/root**

**Comment by Parmama** [comment]
@hegyhati I don't know if you get the **notification** from the **issue**. I don't want to hurry You, I just **tag you** in order to make sure, you get it.   
(Based on this post: https://github.com/orgs/Teaching-projects/teams/sze-mosze-2020/discussions/10)

**Comment by hegyhati** [comment]
done. Mostanaban nem szokott gond lenni, de valamiert errol nem kaptam, jo hogy szoltal.

**Comment by Parmama** [comment]
Köszönöm!
